### ISSUE TITLE
login admin issue

### ISSUE THREAD

**Issue by lagkdok** [boroji/CMS#2]
hi,
there are 2 problems when login to admin zone:
1- anyone can log to admin panel without check user and password there for the script needs login.php
2- even i log to admin panel with users gven in database, the login widget still show username and password

and there is one ore thing, profile.php in admin panel does'nt have save button 

thank you

**Comment by boroji** [comment]
Hi,

Here is the commit that addresses the issue c22aa1083c1bdfc5d7a078e2e434bdac29ad8961

I have added the save button in the profile section on admin page and added extra validation steps for login. It will prevent users from logging in if wrong credentials are entered.

` if ($username === $db_user_name && $password === $db_user_password) {
        header("Location: ../admin");
        $_SESSION['username'] = $db_user_name;
        $_SESSION['user_name'] = $db_user_fullname;
        $_SESSION['user_password'] = $db_user_password;
        
    } else if($username !== $db_user_name && $password !== $db_user_password) {
        header("Location: ../index.php");
    } else if (empty($username) || empty($password)) {
        header("Location: ../index.php");
    } else if ($username === ' ' || $password === ' ') {
        header("Location: ../index.php");
    } else {
        header("Location: ../index.php");
    }`

Please let me know if there is still any security breach regarding login.

Regards,
Hossein

**Comment by lagkdok** [comment]
thank you so much for your fast response but still have the 2nd issue : the login widget sill shown even the admin log in and should have a link for example in the navigation "if admin" in order to get the adminpanel
another request please, is it possible to add subcategories
![fdrd](https://user-images.githubusercontent.com/5101035/83338103-261c5400-a2c1-11ea-8e66-52ec43f6e241.png)
